### ISSUE TITLE
Zug nicht ausgewählt nach Portalwechsel

### ISSUE THREAD

**Issue by Ceddix** [CraftTogetherMC/TC-Portals#2]
Hi 👋🏼 

Mir ist eben eine kleine Sache aufgefallen, und zwar;
Nachdem man durch ein Portal fährt, ist der Zug nicht mehr ausgewählt. Das bedeutet, dass wenn ich nach dem Portalwechsel einen Befehl, wie z.B. `/train maxspeed` nutze, wird mir gesagt, dass ich in keinem Zug sitze.

Wenn ich kurz zwischen den Zügen wechsle, funktioniert es daher wieder. Ist also nur ein kleines Detail und natürlich nicht schlimm, wenn man da nichts machen kann 😄

**Comment by J0schlZ** [comment]
Ist gefixt
